### ISSUE TITLE
Comparison with exiting libraries

### ISSUE THREAD

**Issue by dandv** [mdevils/html-entities#43]
Hi, thanks for publishing this library!

How does it compare with @mathiasbynens's [he](https://github.com/mathiasbynens/he) library, which is more popular on GitHub and NPM?

How about @fb55's `entities`? That library wins in a [performance comparison](https://github.com/fb55/entities#performance) with this one.

**Comment by mdevils** [comment]
Hello @dandv,

Sorry for a delay in the response.

> How does it compare with @mathiasbynens's he library, which is more popular on GitHub and NPM?

Not sure how to answer that question. Check README's and focus on the differences which are important to you.

> How about @fb55's entities? That library wins in a performance comparison with this one.

The benchmark provided by `entities` is very questionable.
There is a benchmark in this repo which I'd consider more statistically significant.

Hope this answers your questions.

**Comment by fb55** [comment]
Have a look at https://github.com/fb55/entities/issues/377 for an in-depth discussion of the benchmarks. Tl;dr the benchmarks measure different things. If you are building a CLI, `html-entities` seems to perform better (for non-JIT compiled code), otherwise you might still want to have a look at `entities`.
